openapi: 3.2.0
info:
  title: yatai api server lago plan API
  description: This is yatai api server.
  version: 1.0.0
tags:
- name: lago plan
  description: lago plan api
paths:
  /api/v1/lago/plans:
    get:
      tags:
      - lago plan
      summary: List lago plans
      operationId: List lago plans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schemasv1LagoPlanListSchema'
    post:
      tags:
      - lago plan
      summary: Create lago plan
      operationId: Create lago plan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Create_Lago_PlanInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schemasv1Plan'
  /api/v1/lago/plans/{planName}:
    put:
      tags:
      - lago plan
      summary: Update lago plan
      operationId: Update lago plan
      parameters:
      - name: planName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update_Lago_PlanInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schemasv1Plan'
components:
  schemas:
    Update_Lago_PlanInput:
      type: object
      properties:
        charges:
          type: array
          items:
            $ref: '#/components/schemas/Schemasv1Charge'
        description:
          type:
          - string
          - 'null'
        display_name:
          type:
          - string
          - 'null'
    Schemasv1Plan:
      type: object
      properties:
        charges:
          type: array
          items:
            $ref: '#/components/schemas/Schemasv1Charge'
        description:
          type: string
        display_name:
          type: string
        lago_id:
          type: string
        name:
          type: string
    Schemasv1LagoPlanListSchema:
      type: object
      properties:
        count:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/Schemasv1Plan'
        start:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
    Schemasv1Charge:
      type: object
      properties:
        price:
          type: string
        resource_instance:
          type: string
    Create_Lago_PlanInput:
      type: object
      properties:
        charges:
          type: array
          items:
            $ref: '#/components/schemas/Schemasv1Charge'
        description:
          type: string
        display_name:
          type: string
        name:
          type: string
  securitySchemes:
    apiToken:
      type: apiKey
      in: header
      name: X-YATAI-API-TOKEN
