openapi: 3.2.0
info:
  title: yatai api server limit group resource API
  description: This is yatai api server.
  version: 1.0.0
tags:
- name: limit group resource
  description: limit group resource
paths:
  /api/admin/v1/limit_groups/{limitGroupName}:
    get:
      tags:
      - limit group resource
      summary: Get a limit group
      operationId: Get a limit group
      parameters:
      - name: limitGroupName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type:
                    - string
                    - 'null'
                  created_at:
                    type: string
                    format: date-time
                  deleted_at:
                    type:
                    - string
                    - 'null'
                    format: date-time
                  description:
                    type: string
                  display_name:
                    type: string
                  labels:
                    type: array
                    items:
                      $ref: '#/components/schemas/ModelschemasLabelItemSchema'
                  name:
                    type: string
                  plan_code:
                    type: string
                  resource_instance_list:
                    type: array
                    items:
                      $ref: '#/components/schemas/Schemasv1ResourceInstanceWithActiveSchema'
                  resource_type:
                    type: string
                    enum:
                    - user
                    - organization
                    - cluster
                    - host_cluster
                    - bento_repository
                    - bento
                    - deployment
                    - deployment_revision
                    - model_repository
                    - model
                    - api_token
                  uid:
                    type: string
                  updated_at:
                    type: string
                    format: date-time
                  visible:
                    type:
                    - boolean
                    - 'null'
    delete:
      tags:
      - limit group resource
      summary: Delete a limit group
      operationId: Delete a limit group
      parameters:
      - name: limitGroupName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type:
                    - string
                    - 'null'
                  created_at:
                    type: string
                    format: date-time
                  deleted_at:
                    type:
                    - string
                    - 'null'
                    format: date-time
                  description:
                    type: string
                  display_name:
                    type: string
                  labels:
                    type: array
                    items:
                      $ref: '#/components/schemas/ModelschemasLabelItemSchema'
                  name:
                    type: string
                  plan_code:
                    type: string
                  resource_instance_list:
                    type: array
                    items:
                      $ref: '#/components/schemas/Schemasv1ResourceInstanceWithActiveSchema'
                  resource_type:
                    type: string
                    enum:
                    - user
                    - organization
                    - cluster
                    - host_cluster
                    - bento_repository
                    - bento
                    - deployment
                    - deployment_revision
                    - model_repository
                    - model
                    - api_token
                  uid:
                    type: string
                  updated_at:
                    type: string
                    format: date-time
                  visible:
                    type:
                    - boolean
                    - 'null'
    patch:
      tags:
      - limit group resource
      summary: Update a limit group
      operationId: Update a limit group
      parameters:
      - name: limitGroupName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update_A_Limit_GroupInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type:
                    - string
                    - 'null'
                  created_at:
                    type: string
                    format: date-time
                  deleted_at:
                    type:
                    - string
                    - 'null'
                    format: date-time
                  description:
                    type: string
                  display_name:
                    type: string
                  labels:
                    type: array
                    items:
                      $ref: '#/components/schemas/ModelschemasLabelItemSchema'
                  name:
                    type: string
                  plan_code:
                    type: string
                  resource_instance_list:
                    type: array
                    items:
                      $ref: '#/components/schemas/Schemasv1ResourceInstanceWithActiveSchema'
                  resource_type:
                    type: string
                    enum:
                    - user
                    - organization
                    - cluster
                    - host_cluster
                    - bento_repository
                    - bento
                    - deployment
                    - deployment_revision
                    - model_repository
                    - model
                    - api_token
                  uid:
                    type: string
                  updated_at:
                    type: string
                    format: date-time
                  visible:
                    type:
                    - boolean
                    - 'null'
components:
  schemas:
    ModelschemasLabelItemSchema:
      type: object
      properties:
        key:
          type: string
        stage:
          type: string
        value:
          type: string
    Schemasv1ResourceInstanceWithActiveSchema:
      type: object
      properties:
        active:
          type: boolean
        resource_instance:
          type: object
          properties:
            config:
              type:
              - string
              - 'null'
            created_at:
              type: string
              format: date-time
            deleted_at:
              type:
              - string
              - 'null'
              format: date-time
            description:
              type: string
            display_name:
              type: string
            labels:
              type: array
              items:
                $ref: '#/components/schemas/ModelschemasLabelItemSchema'
            lago_id:
              type: string
            name:
              type: string
            resource_type:
              type: string
              enum:
              - user
              - organization
              - cluster
              - host_cluster
              - bento_repository
              - bento
              - deployment
              - deployment_revision
              - model_repository
              - model
              - api_token
            uid:
              type: string
            updated_at:
              type: string
              format: date-time
    Update_A_Limit_GroupInput:
      type: object
      properties:
        config:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        display_name:
          type:
          - string
          - 'null'
        plan_code:
          type:
          - string
          - 'null'
        visible:
          type:
          - boolean
          - 'null'
  securitySchemes:
    apiToken:
      type: apiKey
      in: header
      name: X-YATAI-API-TOKEN
