openapi: 3.0.1
info:
  title: yatai api server admin api v1 organization secrets with template API
  description: This is yatai api server.
  version: 1.0.0
tags:
- name: organization secrets with template
  description: organization secrets with template
paths:
  /api/v1/org_secrets_template:
    get:
      tags:
      - organization secrets with template
      summary: List secret template
      operationId: List secret template
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Controllersv1SecretTemplate'
components:
  schemas:
    ModelschemasSecretNoValueItem:
      type: object
      properties:
        key:
          type: string
        sub_path:
          type: string
    ModelschemasSecretNoValueContent:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ModelschemasSecretNoValueItem'
        path:
          type: string
        stage:
          type: string
        type:
          type: string
    Controllersv1SecretTemplate:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/ModelschemasSecretNoValueContent'
        description:
          type: string
        icon:
          type: string
        name:
          type: string
  securitySchemes:
    apiToken:
      type: apiKey
      in: header
      name: X-YATAI-API-TOKEN
